### ISSUE TITLE
String formatting for dates older than 1848 is not consistent

### ISSUE THREAD

**Issue by yregaieg** [Alfresco/alfresco-core#5]
When a property of type d:date contains a value that is older than 1848, the OOTB `ISO8601DateFormat` formats it in the server timezone instead of the default (UTC) used for persistance and to provide a value to SOLR.
This formatting issues can result in solr chuncking on documents having such values in d:date/d:datetime fields.
For more information refer to : https://issues.alfresco.com/jira/browse/ALF-21965

**Comment by derekhulley** [comment]
Thank you.  We will handle the MR and ALF issue and get this included subject to a quick review.
